import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/dogdogapp/generatedmainwidget1/generated/GeneratedFrame4Widget.dart';
import 'package:flutterapp/dogdogapp/generatedmainwidget1/generated/GeneratedStatusBarWidget1.dart';

/* Frame main
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMainWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 358.0,
        height: 652.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Image.asset(
                  "assets/images/61ed2bf05a914bb76ddc4c0afaf1f21c86f98a64.png",
                  color: null,
                  fit: BoxFit.cover,
                  width: 358.0,
                  height: 652.0,
                  colorBlendMode: BlendMode.dstATop,
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 1.047486033519553;

                  final double height =
                      constraints.maxHeight * 0.06748466257668712;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * -0.0223463687150838,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedStatusBarWidget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 1.0139664804469273;

                  final double height =
                      constraints.maxHeight * 0.0950920245398773;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * -0.013966480446927373,
                        y: constraints.maxHeight * 0.9049079754601227,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedFrame4Widget(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
