import 'package:flutter/material.dart';
import 'package:flutterapp/dogdogapp/generatedlist3widget/generated/GeneratedWidget62.dart';
import 'package:flutterapp/dogdogapp/generatedlist3widget/generated/GeneratedVectorWidget626.dart';
import 'package:flutterapp/dogdogapp/generatedlist3widget/generated/GeneratedB2ButtonWidget.dart';
import 'package:flutterapp/dogdogapp/generatedlist3widget/generated/GeneratedB4Widget2.dart';
import 'package:flutterapp/dogdogapp/generatedlist3widget/generated/GeneratedB1ButtonWidget.dart';
import 'package:flutterapp/dogdogapp/generatedlist3widget/generated/GeneratedFrame5Widget1.dart';
import 'package:flutterapp/dogdogapp/generatedlist3widget/generated/GeneratedB3ButtonWidget.dart';
import 'package:flutterapp/dogdogapp/generatedlist3widget/generated/GeneratedB3Widget2.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/dogdogapp/generatedlist3widget/generated/GeneratedB5Widget2.dart';
import 'package:flutterapp/dogdogapp/generatedlist3widget/generated/GeneratedB1Widget2.dart';
import 'package:flutterapp/dogdogapp/generatedlist3widget/generated/GeneratedB2Widget1.dart';
import 'package:flutterapp/dogdogapp/generatedlist3widget/generated/GeneratedB5ButtonWidget.dart';
import 'package:flutterapp/dogdogapp/generatedlist3widget/generated/GeneratedB4ButtonWidget.dart';

/* Frame list3
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedList3Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 114.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 144.0,
                height: 61.0,
                child: GeneratedWidget62(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.4083333333333333;

                  final double height = constraints.maxHeight * 0.075;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.49444444444444446,
                        y: constraints.maxHeight * 0.3015625,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedB2ButtonWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.4083333333333333;

                  final double height = constraints.maxHeight * 0.075;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.49444444444444446,
                        y: constraints.maxHeight * 0.140625,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedB1ButtonWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.4083333333333333;

                  final double height = constraints.maxHeight * 0.075;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.49444444444444446,
                        y: constraints.maxHeight * 0.4625,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedB3ButtonWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.4083333333333333;

                  final double height = constraints.maxHeight * 0.075;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.5,
                        y: constraints.maxHeight * 0.6234375,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedB4ButtonWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.43333333333333335;

                  final double height = constraints.maxHeight * 0.0828125;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.49444444444444446,
                        y: constraints.maxHeight * 0.76875,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedB5ButtonWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 16.0,
                top: 79.0,
                right: null,
                bottom: null,
                width: 115.0,
                height: 71.0,
                child: GeneratedB1Widget2(),
              ),
              Positioned(
                left: 13.0,
                top: 184.0,
                right: null,
                bottom: null,
                width: 115.0,
                height: 71.0,
                child: GeneratedB2Widget1(),
              ),
              Positioned(
                left: 16.0,
                top: 294.0,
                right: null,
                bottom: null,
                width: 115.0,
                height: 71.0,
                child: GeneratedB3Widget2(),
              ),
              Positioned(
                left: 16.0,
                top: 399.0,
                right: null,
                bottom: null,
                width: 115.0,
                height: 71.0,
                child: GeneratedB4Widget2(),
              ),
              Positioned(
                left: 16.0,
                top: 492.0,
                right: null,
                bottom: null,
                width: 115.0,
                height: 71.0,
                child: GeneratedB5Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.06944444444444445;
                  double scaleX = (constraints.maxWidth * percentWidth) / 25.0;

                  double percentHeight = 0.0390625;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 25.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.03611111111111111,
                        translateY: constraints.maxHeight * 0.025,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget626())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 1.0083333333333333;

                  final double height = constraints.maxHeight * 0.096875;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: constraints.maxHeight * 0.903125,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedFrame5Widget1(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
