import 'package:flutter/material.dart';
import 'package:flutterapp/dogdogapp/generatedidpwfindwidget/generated/GeneratedWidget8.dart';
import 'package:flutterapp/dogdogapp/generatedidpwfindwidget/generated/GeneratedP_ComponentWidget1.dart';
import 'package:flutterapp/dogdogapp/generatedidpwfindwidget/generated/GeneratedButtonWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/dogdogapp/generatedidpwfindwidget/generated/GeneratedVectorWidget3.dart';
import 'package:flutterapp/dogdogapp/generatedidpwfindwidget/generated/GeneratedI_ComponentWidget1.dart';
import 'package:flutterapp/dogdogapp/generatedidpwfindwidget/generated/GeneratedRectangle20Widget1.dart';
import 'package:flutterapp/dogdogapp/generatedidpwfindwidget/generated/GeneratedIdf_ButtonWidget.dart';

/* Frame id/pw find
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIdpwfindWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 366.0,
        height: 632.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 26.0,
                top: 115.0,
                right: null,
                bottom: null,
                width: 311.0,
                height: 46.0,
                child: GeneratedI_ComponentWidget1(),
              ),
              Positioned(
                left: 29.0,
                top: 208.0,
                right: null,
                bottom: null,
                width: 311.0,
                height: 46.0,
                child: GeneratedP_ComponentWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 374.0,
                height: 46.0,
                child: GeneratedRectangle20Widget1(),
              ),
              Positioned(
                left: 56.0,
                top: 16.0,
                right: null,
                bottom: null,
                width: 262.0,
                height: 32.0,
                child: GeneratedWidget8(),
              ),
              Positioned(
                left: 27.0,
                top: 145.0,
                right: null,
                bottom: null,
                width: 311.0,
                height: 46.0,
                child: GeneratedIdf_ButtonWidget(),
              ),
              Positioned(
                left: 26.0,
                top: 291.0,
                right: null,
                bottom: null,
                width: 311.0,
                height: 46.0,
                child: GeneratedButtonWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.06830601092896176;
                  double scaleX = (constraints.maxWidth * percentWidth) / 25.0;

                  double percentHeight = 0.03955696202531646;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 25.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.0273224043715847,
                        translateY: constraints.maxHeight * 0.02531645569620253,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget3())
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
