import 'package:flutter/material.dart';
import 'package:flutterapp/dogdogapp/generatedlist2widget/generated/GeneratedWidget31.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/dogdogapp/generatedlist2widget/generated/GeneratedM4Widget.dart';
import 'package:flutterapp/dogdogapp/generatedlist2widget/generated/GeneratedFrame6Widget1.dart';
import 'package:flutterapp/dogdogapp/generatedlist2widget/generated/GeneratedM2ButtonWidget.dart';
import 'package:flutterapp/dogdogapp/generatedlist2widget/generated/GeneratedM3ButtonWidget.dart';
import 'package:flutterapp/dogdogapp/generatedlist2widget/generated/GeneratedM1Widget.dart';
import 'package:flutterapp/dogdogapp/generatedlist2widget/generated/GeneratedM5Widget.dart';
import 'package:flutterapp/dogdogapp/generatedlist2widget/generated/GeneratedM1ButtonWidget.dart';
import 'package:flutterapp/dogdogapp/generatedlist2widget/generated/GeneratedM2Widget.dart';
import 'package:flutterapp/dogdogapp/generatedlist2widget/generated/GeneratedM4ButtonWidget.dart';
import 'package:flutterapp/dogdogapp/generatedlist2widget/generated/GeneratedM5ButtonWidget.dart';
import 'package:flutterapp/dogdogapp/generatedlist2widget/generated/GeneratedVectorWidget130.dart';
import 'package:flutterapp/dogdogapp/generatedlist2widget/generated/GeneratedM3Widget.dart';

/* Frame list2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedList2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 87.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 191.0,
                height: 63.0,
                child: GeneratedWidget31(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.4083333333333333;

                  final double height = constraints.maxHeight * 0.075;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.5222222222222223,
                        y: constraints.maxHeight * 0.30625,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedM2ButtonWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.4083333333333333;

                  final double height = constraints.maxHeight * 0.075;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.5222222222222223,
                        y: constraints.maxHeight * 0.459375,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedM3ButtonWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.4083333333333333;

                  final double height = constraints.maxHeight * 0.075;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.525,
                        y: constraints.maxHeight * 0.628125,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedM4ButtonWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.4083333333333333;

                  final double height = constraints.maxHeight * 0.075;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.5222222222222223,
                        y: constraints.maxHeight * 0.775,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedM5ButtonWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.4083333333333333;

                  final double height = constraints.maxHeight * 0.075;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.5222222222222223,
                        y: constraints.maxHeight * 0.16875,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedM1ButtonWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 24.0,
                top: 97.0,
                right: null,
                bottom: null,
                width: 115.0,
                height: 71.0,
                child: GeneratedM1Widget(),
              ),
              Positioned(
                left: 24.0,
                top: 391.0,
                right: null,
                bottom: null,
                width: 115.0,
                height: 71.0,
                child: GeneratedM4Widget(),
              ),
              Positioned(
                left: 24.0,
                top: 489.0,
                right: null,
                bottom: null,
                width: 115.0,
                height: 71.0,
                child: GeneratedM5Widget(),
              ),
              Positioned(
                left: 24.0,
                top: 284.0,
                right: null,
                bottom: null,
                width: 115.0,
                height: 71.0,
                child: GeneratedM3Widget(),
              ),
              Positioned(
                left: 24.0,
                top: 185.0,
                right: null,
                bottom: null,
                width: 115.0,
                height: 71.0,
                child: GeneratedM2Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.06944444444444445;
                  double scaleX = (constraints.maxWidth * percentWidth) / 25.0;

                  double percentHeight = 0.0390625;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 25.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.03333333333333333,
                        translateY: constraints.maxHeight * 0.01875,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget130())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 1.0083333333333333;

                  final double height = constraints.maxHeight * 0.096875;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * -0.008333333333333333,
                        y: constraints.maxHeight * 0.903125,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedFrame6Widget1(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
