import 'package:flutter/material.dart';
import 'package:flutterapp/dogdogapp/generatedregisterwidget/generated/GeneratedN_ComponentWidget.dart';
import 'package:flutterapp/dogdogapp/generatedregisterwidget/generated/GeneratedWidget11.dart';
import 'package:flutterapp/dogdogapp/generatedregisterwidget/generated/GeneratedR_ButtonWidget1.dart';
import 'package:flutterapp/dogdogapp/generatedregisterwidget/generated/GeneratedI_ComponentWidget2.dart';
import 'package:flutterapp/dogdogapp/generatedregisterwidget/generated/GeneratedCP_ComponentWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/dogdogapp/generatedregisterwidget/generated/GeneratedP_ComponentWidget2.dart';
import 'package:flutterapp/dogdogapp/generatedregisterwidget/generated/GeneratedVectorWidget4.dart';
import 'package:flutterapp/dogdogapp/generatedregisterwidget/generated/GeneratedRectangle21Widget.dart';

/* Frame register
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRegisterWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 661.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 9.0,
                top: 88.0,
                right: null,
                bottom: null,
                width: 342.0,
                height: 48.0,
                child: GeneratedN_ComponentWidget(),
              ),
              Positioned(
                left: 9.0,
                top: 164.0,
                right: null,
                bottom: null,
                width: 342.0,
                height: 48.0,
                child: GeneratedI_ComponentWidget2(),
              ),
              Positioned(
                left: 9.0,
                top: 314.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 49.0,
                child: GeneratedCP_ComponentWidget(),
              ),
              Positioned(
                left: 8.0,
                top: 240.0,
                right: null,
                bottom: null,
                width: 342.0,
                height: 46.0,
                child: GeneratedP_ComponentWidget2(),
              ),
              Positioned(
                left: -10.0,
                top: 30.0,
                right: null,
                bottom: null,
                width: 260.0,
                height: 41.0,
                child: GeneratedRectangle21Widget(),
              ),
              Positioned(
                left: 47.0,
                top: 20.0,
                right: null,
                bottom: null,
                width: 265.0,
                height: 35.0,
                child: GeneratedWidget11(),
              ),
              Positioned(
                left: 9.0,
                top: 401.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 49.0,
                child: GeneratedR_ButtonWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.06944444444444445;
                  double scaleX = (constraints.maxWidth * percentWidth) / 25.0;

                  double percentHeight = 0.037821482602118005;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 25.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.022222222222222223,
                        translateY: constraints.maxHeight * 0.03479576399394856,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget4())
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
