import 'package:flutter/material.dart';
import 'package:flutterapp/dogdogapp/generatedmainwidget/generated/GeneratedR_ButtonWidget.dart';
import 'package:flutterapp/dogdogapp/generatedmainwidget/generated/GeneratedTouchappWidget.dart';
import 'package:flutterapp/dogdogapp/generatedmainwidget/generated/GeneratedStatusBarWidget.dart';
import 'package:flutterapp/dogdogapp/generatedmainwidget/generated/GeneratedLogin_ButtonWidget.dart';
import 'package:flutterapp/dogdogapp/generatedmainwidget/generated/GeneratedWidget3.dart';

/* Frame main
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMainWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 366.0,
              height: 652.0,
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Image.asset(
                        "assets/images/61ed2bf05a914bb76ddc4c0afaf1f21c86f98a64.png",
                        color: null,
                        fit: BoxFit.cover,
                        width: 366.0,
                        height: 652.0,
                        colorBlendMode: BlendMode.dstATop,
                      ),
                    ),
                    Positioned(
                      left: 17.0,
                      top: 543.0,
                      right: null,
                      bottom: null,
                      width: 155.0,
                      height: 50.0,
                      child: GeneratedLogin_ButtonWidget(),
                    ),
                    Positioned(
                      left: 191.0,
                      top: 542.0,
                      right: null,
                      bottom: null,
                      width: 155.0,
                      height: 50.0,
                      child: GeneratedR_ButtonWidget(),
                    ),
                    Positioned(
                      left: 113.0,
                      top: 108.0,
                      right: null,
                      bottom: null,
                      width: 160.0,
                      height: 50.0,
                      child: GeneratedWidget3(),
                    )
                  ]),
            ),
            Positioned(
              left: 17.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 44.0,
              child: GeneratedStatusBarWidget(),
            ),
            Positioned(
              left: 260.0,
              top: 106.0,
              right: null,
              bottom: null,
              width: 52.0,
              height: 50.0,
              child: GeneratedTouchappWidget(),
            )
          ]),
    ));
  }
}
