import 'package:flutter/material.dart';
import 'package:flutterapp/dogdogapp/generateddog2widget/generated/GeneratedFrame8Widget1.dart';
import 'package:flutterapp/dogdogapp/generateddog2widget/generated/Generated3001937Widget.dart';
import 'package:flutterapp/dogdogapp/generateddog2widget/generated/GeneratedWidget60.dart';
import 'package:flutterapp/dogdogapp/generateddog2widget/generated/GeneratedVectorWidget595.dart';
import 'package:flutterapp/dogdogapp/generateddog2widget/generated/GeneratedWidget61.dart';
import 'package:flutterapp/helpers/transform/transform.dart';

/* Frame dog2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDog2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 268.0,
                right: null,
                bottom: null,
                width: 362.0,
                height: 281.0,
                child: Generated3001937Widget(),
              ),
              Positioned(
                left: 49.0,
                top: 10.0,
                right: null,
                bottom: null,
                width: 265.0,
                height: 35.0,
                child: GeneratedWidget60(),
              ),
              Positioned(
                left: 22.0,
                top: 90.0,
                right: null,
                bottom: null,
                width: 314.0,
                height: 139.0,
                child: GeneratedWidget61(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.06944444444444445;
                  double scaleX = (constraints.maxWidth * percentWidth) / 25.0;

                  double percentHeight = 0.0390625;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 25.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.027777777777777776,
                        translateY: constraints.maxHeight * 0.015625,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget595())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 1.0083333333333333;

                  final double height = constraints.maxHeight * 0.096875;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: constraints.maxHeight * 0.903125,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedFrame8Widget1(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
