import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/dogdogapp/generatedinfoeditwidget/generated/GeneratedVectorWidget66.dart';
import 'package:flutterapp/dogdogapp/generatedinfoeditwidget/generated/GeneratedN_ComponentWidget1.dart';
import 'package:flutterapp/dogdogapp/generatedinfoeditwidget/generated/GeneratedInfo_ButtonWidget.dart';
import 'package:flutterapp/dogdogapp/generatedinfoeditwidget/generated/GeneratedI_ComponentWidget4.dart';
import 'package:flutterapp/dogdogapp/generatedinfoeditwidget/generated/GeneratedWidget17.dart';

/* Frame info edit
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedInfoeditWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.95;

                  final double height = constraints.maxHeight * 0.075;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.025,
                        y: constraints.maxHeight * 0.2234375,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedI_ComponentWidget4(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.7361111111111112;

                  final double height = constraints.maxHeight * 0.0546875;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.1388888888888889,
                        y: constraints.maxHeight * 0.01875,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedWidget17(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.95;

                  final double height = constraints.maxHeight * 0.075;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.025,
                        y: constraints.maxHeight * 0.340625,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedInfo_ButtonWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.95;

                  final double height = constraints.maxHeight * 0.075;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.025,
                        y: constraints.maxHeight * 0.125,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedN_ComponentWidget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.06944444444444445;
                  double scaleX = (constraints.maxWidth * percentWidth) / 25.0;

                  double percentHeight = 0.0390625;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 25.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.025,
                        translateY: constraints.maxHeight * 0.01875,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget66())
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
