import 'package:flutter/material.dart';
import 'package:flutterapp/dogdogapp/generatedloginwidget/generated/GeneratedWidget5.dart';
import 'package:flutterapp/dogdogapp/generatedloginwidget/generated/GeneratedVectorWidget2.dart';
import 'package:flutterapp/dogdogapp/generatedloginwidget/generated/GeneratedLogin_ButtonWidget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/dogdogapp/generatedloginwidget/generated/GeneratedRectangle20Widget.dart';
import 'package:flutterapp/dogdogapp/generatedloginwidget/generated/GeneratedP_ComponentWidget.dart';
import 'package:flutterapp/dogdogapp/generatedloginwidget/generated/GeneratedI_ComponentWidget.dart';
import 'package:flutterapp/dogdogapp/generatedloginwidget/generated/GeneratedIdpw_F_ButtonWidget.dart';

/* Frame login
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLoginWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 373.0,
        height: 652.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 29.0,
                top: 83.0,
                right: null,
                bottom: null,
                width: 311.0,
                height: 46.0,
                child: GeneratedI_ComponentWidget(),
              ),
              Positioned(
                left: 29.0,
                top: 144.0,
                right: null,
                bottom: null,
                width: 311.0,
                height: 46.0,
                child: GeneratedP_ComponentWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 374.0,
                height: 46.0,
                child: GeneratedRectangle20Widget(),
              ),
              Positioned(
                left: 56.0,
                top: 16.0,
                right: null,
                bottom: null,
                width: 265.0,
                height: 35.0,
                child: GeneratedWidget5(),
              ),
              Positioned(
                left: 29.0,
                top: 216.0,
                right: null,
                bottom: null,
                width: 311.0,
                height: 46.0,
                child: GeneratedLogin_ButtonWidget1(),
              ),
              Positioned(
                left: 29.0,
                top: 277.0,
                right: null,
                bottom: null,
                width: 311.0,
                height: 46.0,
                child: GeneratedIdpw_F_ButtonWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.06702412868632708;
                  double scaleX = (constraints.maxWidth * percentWidth) / 25.0;

                  double percentHeight = 0.03834355828220859;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 25.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.032171581769437,
                        translateY:
                            constraints.maxHeight * 0.029141104294478526,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget2())
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
