import 'package:flutter/material.dart';
import 'package:flutterapp/dogdogapp/generateddog1widget/generated/GeneratedWidget37.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/dogdogapp/generateddog1widget/generated/GeneratedB1Widget.dart';
import 'package:flutterapp/dogdogapp/generateddog1widget/generated/GeneratedVectorWidget161.dart';
import 'package:flutterapp/dogdogapp/generateddog1widget/generated/GeneratedFrame7Widget.dart';
import 'package:flutterapp/dogdogapp/generateddog1widget/generated/GeneratedWidget38.dart';

/* Frame dog1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDog1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 3.0,
                top: 271.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 246.0,
                child: GeneratedWidget37(),
              ),
              Positioned(
                left: 20.0,
                top: 86.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 140.0,
                child: GeneratedB1Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.06944444444444445;
                  double scaleX = (constraints.maxWidth * percentWidth) / 25.0;

                  double percentHeight = 0.0390625;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 25.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.022222222222222223,
                        translateY: constraints.maxHeight * 0.0171875,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget161())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 1.0083333333333333;

                  final double height = constraints.maxHeight * 0.096875;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * -0.011111111111111112,
                        y: constraints.maxHeight * 0.903125,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedFrame7Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 41.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 284.0,
                height: 54.0,
                child: GeneratedWidget38(),
              )
            ]),
      ),
    ));
  }
}
