import 'package:flutter/material.dart';
import 'package:flutterapp/dogdogapp/generateddoglistwidget/generated/GeneratedS_ButtonWidget.dart';
import 'package:flutterapp/dogdogapp/generateddoglistwidget/generated/GeneratedLine2Widget.dart';
import 'package:flutterapp/dogdogapp/generateddoglistwidget/generated/GeneratedB_ButtonWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/dogdogapp/generateddoglistwidget/generated/GeneratedLine1Widget.dart';
import 'package:flutterapp/dogdogapp/generateddoglistwidget/generated/GeneratedEllipse16Widget.dart';
import 'package:flutterapp/dogdogapp/generateddoglistwidget/generated/GeneratedFrame4Widget1.dart';
import 'package:flutterapp/dogdogapp/generateddoglistwidget/generated/GeneratedLine3Widget.dart';
import 'package:flutterapp/dogdogapp/generateddoglistwidget/generated/GeneratedEllipse18Widget.dart';
import 'package:flutterapp/dogdogapp/generateddoglistwidget/generated/GeneratedEllipse19Widget.dart';
import 'package:flutterapp/dogdogapp/generateddoglistwidget/generated/GeneratedM_ButtonWidget.dart';
import 'package:flutterapp/dogdogapp/generateddoglistwidget/generated/GeneratedVectorWidget68.dart';
import 'package:flutterapp/dogdogapp/generateddoglistwidget/generated/GeneratedWidget24.dart';
import 'package:flutterapp/dogdogapp/generateddoglistwidget/generated/GeneratedEllipse17Widget.dart';

/* Frame dog list
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDoglistWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.4083333333333333;

                  final double height = constraints.maxHeight * 0.075;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.49722222222222223,
                        y: constraints.maxHeight * 0.171875,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedS_ButtonWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.4083333333333333;

                  final double height = constraints.maxHeight * 0.075;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.5027777777777778,
                        y: constraints.maxHeight * 0.38125,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedM_ButtonWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.4083333333333333;

                  final double height = constraints.maxHeight * 0.075;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.5027777777777778,
                        y: constraints.maxHeight * 0.6015625,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedB_ButtonWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 50.0,
                top: 9.0,
                right: null,
                bottom: null,
                width: 262.0,
                height: 32.0,
                child: GeneratedWidget24(),
              ),
              Positioned(
                left: 23.0,
                top: 79.0,
                right: null,
                bottom: null,
                width: 115.0,
                height: 99.0,
                child: GeneratedEllipse16Widget(),
              ),
              Positioned(
                left: 23.0,
                top: 360.0,
                right: null,
                bottom: null,
                width: 115.0,
                height: 99.0,
                child: GeneratedEllipse18Widget(),
              ),
              Positioned(
                left: 23.0,
                top: 219.0,
                right: null,
                bottom: null,
                width: 115.0,
                height: 99.0,
                child: GeneratedEllipse17Widget(),
              ),
              Positioned(
                left: 23.0,
                top: 219.0,
                right: null,
                bottom: null,
                width: 115.0,
                height: 99.0,
                child: GeneratedEllipse19Widget(),
              ),
              Positioned(
                left: -0.0027933120727539062,
                top: 204.50001525878906,
                right: null,
                bottom: null,
                width: 357.9973449707031,
                height: 1.9999852180480957,
                child: GeneratedLine1Widget(),
              ),
              Positioned(
                left: -0.0029296875,
                top: 204.5,
                right: null,
                bottom: null,
                width: 357.9973449707031,
                height: 1.9999852180480957,
                child: GeneratedLine2Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 345.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 1.0,
                child: GeneratedLine3Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.06944444444444445;
                  double scaleX = (constraints.maxWidth * percentWidth) / 25.0;

                  double percentHeight = 0.0390625;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 25.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.030555555555555555,
                        translateY: constraints.maxHeight * 0.0203125,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget68())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 1.0083333333333333;

                  final double height = constraints.maxHeight * 0.096875;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * -0.013888888888888888,
                        y: constraints.maxHeight * 0.903125,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedFrame4Widget1(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
