import 'package:flutter/material.dart';
import 'package:flutterapp/dogdogapp/generateduserinfowidget/generated/GeneratedLogout_ButtonWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/dogdogapp/generateduserinfowidget/generated/GeneratedFrame5Widget.dart';
import 'package:flutterapp/dogdogapp/generateduserinfowidget/generated/GeneratedWidget13.dart';
import 'package:flutterapp/dogdogapp/generateduserinfowidget/generated/GeneratedVectorWidget35.dart';
import 'package:flutterapp/dogdogapp/generateduserinfowidget/generated/GeneratedInfo_E_ButtonWidget.dart';
import 'package:flutterapp/dogdogapp/generateduserinfowidget/generated/GeneratedEllipse15Widget.dart';
import 'package:flutterapp/dogdogapp/generateduserinfowidget/generated/GeneratedI_ComponentWidget3.dart';
import 'package:flutterapp/dogdogapp/generateduserinfowidget/generated/GeneratedPE_ButtonWidget.dart';

/* Frame user info
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedUserinfoWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 670.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.7361111111111112;

                  final double height =
                      constraints.maxHeight * 0.0791044776119403;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.1388888888888889,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedWidget13(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.4027777777777778;

                  final double height =
                      constraints.maxHeight * 0.07014925373134329;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.06666666666666667,
                        y: constraints.maxHeight * 0.3611940298507463,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedInfo_E_ButtonWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.875;

                  final double height =
                      constraints.maxHeight * 0.07313432835820896;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.06666666666666667,
                        y: constraints.maxHeight * 0.4761194029850746,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedLogout_ButtonWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.4027777777777778;

                  final double height =
                      constraints.maxHeight * 0.07014925373134329;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.5388888888888889,
                        y: constraints.maxHeight * 0.3611940298507463,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedPE_ButtonWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.2972222222222222;
                  double scaleX = (constraints.maxWidth * percentWidth) / 107.0;

                  double percentHeight = 0.1582089552238806;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 106.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.044444444444444446,
                        translateY: constraints.maxHeight * 0.11641791044776119,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedEllipse15Widget())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.5722222222222222;

                  final double height =
                      constraints.maxHeight * 0.06865671641791045;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.39444444444444443,
                        y: constraints.maxHeight * 0.11641791044776119,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedI_ComponentWidget3(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.06944444444444445;
                  double scaleX = (constraints.maxWidth * percentWidth) / 25.0;

                  double percentHeight = 0.03731343283582089;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 25.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.022222222222222223,
                        translateY: constraints.maxHeight * 0.01791044776119403,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget35())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 1.0083333333333333;

                  final double height =
                      constraints.maxHeight * 0.09253731343283582;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * -0.002777777777777778,
                        y: constraints.maxHeight * 0.9074626865671642,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedFrame5Widget(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
