import 'package:flutter/material.dart';
import 'package:flutterapp/dogdogapp/generateddog4widget/generated/GeneratedFrame10Widget1.dart';
import 'package:flutterapp/dogdogapp/generateddog4widget/generated/GeneratedB4Widget.dart';
import 'package:flutterapp/dogdogapp/generateddog4widget/generated/GeneratedWidget44.dart';
import 'package:flutterapp/dogdogapp/generateddog4widget/generated/GeneratedWidget43.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/dogdogapp/generateddog4widget/generated/GeneratedVectorWidget285.dart';

/* Frame dog4
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDog4Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 3.0,
                top: 275.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 204.0,
                child: GeneratedWidget43(),
              ),
              Positioned(
                left: 63.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 240.0,
                height: 59.0,
                child: GeneratedB4Widget(),
              ),
              Positioned(
                left: 24.0,
                top: 88.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 136.0,
                child: GeneratedWidget44(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.06944444444444445;
                  double scaleX = (constraints.maxWidth * percentWidth) / 25.0;

                  double percentHeight = 0.0390625;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 25.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.03333333333333333,
                        translateY: constraints.maxHeight * 0.0234375,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget285())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 1.011111111111111;

                  final double height = constraints.maxHeight * 0.096875;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: constraints.maxHeight * 0.903125,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedFrame10Widget1(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
