import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/dogdogapp/generateddog10widget/generated/GeneratedVectorWidget316.dart';
import 'package:flutterapp/dogdogapp/generateddog10widget/generated/Generated192Widget.dart';
import 'package:flutterapp/dogdogapp/generateddog10widget/generated/GeneratedFrame12Widget.dart';
import 'package:flutterapp/dogdogapp/generateddog10widget/generated/GeneratedB5Widget1.dart';
import 'package:flutterapp/dogdogapp/generateddog10widget/generated/GeneratedWidget45.dart';

/* Frame dog10
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDog10Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 43.0,
                top: null,
                right: null,
                bottom: null,
                width: 256.0,
                height: 139.0,
                child: TransformHelper.translate(
                    x: 0.00, y: -153.50, z: 0, child: GeneratedB5Widget1()),
              ),
              Positioned(
                left: 63.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 237.0,
                height: 66.0,
                child: GeneratedWidget45(),
              ),
              Positioned(
                left: 16.0,
                top: 277.0,
                right: null,
                bottom: null,
                width: 312.0,
                height: 249.0,
                child: Generated192Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.06944444444444445;
                  double scaleX = (constraints.maxWidth * percentWidth) / 25.0;

                  double percentHeight = 0.0390625;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 25.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.05,
                        translateY: constraints.maxHeight * 0.03125,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget316())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 1.0083333333333333;

                  final double height = constraints.maxHeight * 0.096875;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: constraints.maxHeight * 0.903125,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedFrame12Widget(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
