import 'package:flutter/material.dart';
import 'package:flutterapp/dogdogapp/generatedlist1widget/generated/GeneratedS4ButtonWidget.dart';
import 'package:flutterapp/dogdogapp/generatedlist1widget/generated/GeneratedVectorWidget99.dart';
import 'package:flutterapp/dogdogapp/generatedlist1widget/generated/GeneratedWidget30.dart';
import 'package:flutterapp/dogdogapp/generatedlist1widget/generated/GeneratedS1Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/dogdogapp/generatedlist1widget/generated/GeneratedS5ButtonWidget.dart';
import 'package:flutterapp/dogdogapp/generatedlist1widget/generated/GeneratedS4Widget.dart';
import 'package:flutterapp/dogdogapp/generatedlist1widget/generated/GeneratedS1ButtonWidget.dart';
import 'package:flutterapp/dogdogapp/generatedlist1widget/generated/GeneratedS3Widget.dart';
import 'package:flutterapp/dogdogapp/generatedlist1widget/generated/GeneratedS2ButtonWidget.dart';
import 'package:flutterapp/dogdogapp/generatedlist1widget/generated/GeneratedFrame6Widget.dart';
import 'package:flutterapp/dogdogapp/generatedlist1widget/generated/GeneratedS5Widget.dart';
import 'package:flutterapp/dogdogapp/generatedlist1widget/generated/GeneratedS3ButtonWidget.dart';
import 'package:flutterapp/dogdogapp/generatedlist1widget/generated/GeneratedS2Widget.dart';

/* Frame list1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedList1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.4083333333333333;

                  final double height = constraints.maxHeight * 0.075;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.5277777777777778,
                        y: constraints.maxHeight * 0.1609375,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedS1ButtonWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.4083333333333333;

                  final double height = constraints.maxHeight * 0.075;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.5305555555555556,
                        y: constraints.maxHeight * 0.315625,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedS2ButtonWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.4083333333333333;

                  final double height = constraints.maxHeight * 0.075;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.5361111111111111,
                        y: constraints.maxHeight * 0.4703125,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedS3ButtonWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.4083333333333333;

                  final double height = constraints.maxHeight * 0.075;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.5361111111111111,
                        y: constraints.maxHeight * 0.6265625,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedS4ButtonWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.4083333333333333;

                  final double height = constraints.maxHeight * 0.075;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.5361111111111111,
                        y: constraints.maxHeight * 0.7875,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedS5ButtonWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 87.0,
                top: -4.0,
                right: null,
                bottom: null,
                width: 184.0,
                height: 70.0,
                child: GeneratedWidget30(),
              ),
              Positioned(
                left: 25.0,
                top: 91.0,
                right: null,
                bottom: null,
                width: 115.0,
                height: 71.0,
                child: GeneratedS1Widget(),
              ),
              Positioned(
                left: 25.0,
                top: 190.0,
                right: null,
                bottom: null,
                width: 112.0,
                height: 71.0,
                child: GeneratedS2Widget(),
              ),
              Positioned(
                left: 25.0,
                top: 290.0,
                right: null,
                bottom: null,
                width: 115.0,
                height: 71.0,
                child: GeneratedS3Widget(),
              ),
              Positioned(
                left: 24.0,
                top: 394.0,
                right: null,
                bottom: null,
                width: 115.0,
                height: 71.0,
                child: GeneratedS4Widget(),
              ),
              Positioned(
                left: 24.0,
                top: 493.0,
                right: null,
                bottom: null,
                width: 115.0,
                height: 71.0,
                child: GeneratedS5Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.06944444444444445;
                  double scaleX = (constraints.maxWidth * percentWidth) / 25.0;

                  double percentHeight = 0.0390625;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 25.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.03611111111111111,
                        translateY: constraints.maxHeight * 0.01875,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget99())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 1.0083333333333333;

                  final double height = constraints.maxHeight * 0.096875;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: constraints.maxHeight * 0.903125,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedFrame6Widget(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
