import 'package:flutter/material.dart';
import 'package:flutterapp/dogdogapp/generatedchatwidget/generated/GeneratedEmojiWidget.dart';
import 'package:flutterapp/dogdogapp/generatedchatwidget/generated/GeneratedRectangle16Widget.dart';
import 'package:flutterapp/dogdogapp/generatedchatwidget/generated/GeneratedVectorWidget662.dart';
import 'package:flutterapp/dogdogapp/generatedchatwidget/generated/GeneratedWidget68.dart';
import 'package:flutterapp/dogdogapp/generatedchatwidget/generated/GeneratedRectangle20Widget2.dart';
import 'package:flutterapp/dogdogapp/generatedchatwidget/generated/GeneratedWidget73.dart';
import 'package:flutterapp/dogdogapp/generatedchatwidget/generated/GeneratedEllipse2Widget.dart';
import 'package:flutterapp/dogdogapp/generatedchatwidget/generated/GeneratedEllipse4Widget.dart';
import 'package:flutterapp/dogdogapp/generatedchatwidget/generated/GeneratedWidget70.dart';
import 'package:flutterapp/dogdogapp/generatedchatwidget/generated/GeneratedFrame6Widget2.dart';
import 'package:flutterapp/dogdogapp/generatedchatwidget/generated/GeneratedWidget71.dart';
import 'package:flutterapp/dogdogapp/generatedchatwidget/generated/GeneratedRectangle21Widget1.dart';
import 'package:flutterapp/dogdogapp/generatedchatwidget/generated/GeneratedRectangle22Widget.dart';
import 'package:flutterapp/dogdogapp/generatedchatwidget/generated/GeneratedWidget69.dart';
import 'package:flutterapp/dogdogapp/generatedchatwidget/generated/GeneratedMessageWidget.dart';
import 'package:flutterapp/dogdogapp/generatedchatwidget/generated/GeneratedRectangle23Widget.dart';
import 'package:flutterapp/dogdogapp/generatedchatwidget/generated/GeneratedEllipse3Widget.dart';
import 'package:flutterapp/dogdogapp/generatedchatwidget/generated/GeneratedRectangle25Widget.dart';
import 'package:flutterapp/dogdogapp/generatedchatwidget/generated/GeneratedWidget72.dart';
import 'package:flutterapp/dogdogapp/generatedchatwidget/generated/GeneratedChoiyongtaeWidget.dart';
import 'package:flutterapp/dogdogapp/generatedchatwidget/generated/GeneratedRectangle24Widget1.dart';
import 'package:flutterapp/dogdogapp/generatedchatwidget/generated/Generated3Widget1.dart';
import 'package:flutterapp/dogdogapp/generatedchatwidget/generated/GeneratedPaperPlaneWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';

/* Frame chat
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedChatWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 295.0,
                top: 517.0,
                right: null,
                bottom: null,
                width: 58.0,
                height: 56.0,
                child: GeneratedEllipse4Widget(),
              ),
              Positioned(
                left: 26.0,
                top: 56.0,
                right: null,
                bottom: null,
                width: 44.0,
                height: 47.0,
                child: GeneratedEllipse2Widget(),
              ),
              Positioned(
                left: 10.0,
                top: 524.0,
                right: null,
                bottom: null,
                width: 277.0,
                height: 42.0,
                child: GeneratedRectangle16Widget(),
              ),
              Positioned(
                left: 88.0,
                top: 535.0,
                right: null,
                bottom: null,
                width: 53.0,
                height: 19.0,
                child: GeneratedMessageWidget(),
              ),
              Positioned(
                left: 60.0,
                top: 103.0,
                right: null,
                bottom: null,
                width: 13.0,
                height: 13.0,
                child: GeneratedEllipse3Widget(),
              ),
              Positioned(
                left: 92.0,
                top: 62.0,
                right: null,
                bottom: null,
                width: 72.0,
                height: 33.0,
                child: GeneratedWidget68(),
              ),
              Positioned(
                left: 87.0,
                top: 88.0,
                right: null,
                bottom: null,
                width: 95.0,
                height: 21.0,
                child: GeneratedChoiyongtaeWidget(),
              ),
              Positioned(
                left: 7.0,
                top: 120.0,
                right: null,
                bottom: null,
                width: 338.0,
                height: 392.0,
                child: GeneratedRectangle20Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.06944444444444445;

                  final double height = constraints.maxHeight * 0.03125;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.075,
                        y: constraints.maxHeight * 0.8375,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedEmojiWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 28.0,
                top: 153.5,
                right: null,
                bottom: null,
                width: 152.0,
                height: 48.0,
                child: GeneratedRectangle21Widget1(),
              ),
              Positioned(
                left: 41.0,
                top: 172.0,
                right: null,
                bottom: null,
                width: 28.0,
                height: 19.0,
                child: GeneratedWidget69(),
              ),
              Positioned(
                left: 28.0,
                top: 288.0,
                right: null,
                bottom: null,
                width: 158.0,
                height: 57.0,
                child: GeneratedRectangle22Widget(),
              ),
              Positioned(
                left: 46.0,
                top: 309.0,
                right: null,
                bottom: null,
                width: 72.0,
                height: 19.0,
                child: GeneratedWidget70(),
              ),
              Positioned(
                left: 31.0,
                top: 418.0,
                right: null,
                bottom: null,
                width: 117.0,
                height: 45.0,
                child: GeneratedRectangle25Widget(),
              ),
              Positioned(
                left: 58.0,
                top: 433.0,
                right: null,
                bottom: null,
                width: 31.0,
                height: 19.0,
                child: GeneratedWidget71(),
              ),
              Positioned(
                left: 176.0,
                top: 365.0,
                right: null,
                bottom: null,
                width: 163.0,
                height: 48.0,
                child: GeneratedRectangle24Widget1(),
              ),
              Positioned(
                left: 186.0,
                top: 210.0,
                right: null,
                bottom: null,
                width: 146.0,
                height: 58.0,
                child: GeneratedRectangle23Widget(),
              ),
              Positioned(
                left: 209.0,
                top: 232.0,
                right: null,
                bottom: null,
                width: 28.0,
                height: 19.0,
                child: GeneratedWidget72(),
              ),
              Positioned(
                left: 207.0,
                top: 382.0,
                right: null,
                bottom: null,
                width: 76.0,
                height: 19.0,
                child: Generated3Widget1(),
              ),
              Positioned(
                left: 102.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 144.0,
                height: 61.0,
                child: GeneratedWidget73(),
              ),
              Positioned(
                left: 309.0,
                top: 533.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedPaperPlaneWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.06944444444444445;
                  double scaleX = (constraints.maxWidth * percentWidth) / 25.0;

                  double percentHeight = 0.0390625;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 25.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.019444444444444445,
                        translateY: constraints.maxHeight * 0.0171875,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget662())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 1.0083333333333333;

                  final double height = constraints.maxHeight * 0.096875;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * -0.002777777777777778,
                        y: constraints.maxHeight * 0.903125,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedFrame6Widget2(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
