import 'package:flutter/material.dart';
import 'package:flutterapp/dogdogapp/generateddog12widget/generated/GeneratedS2Widget1.dart';
import 'package:flutterapp/dogdogapp/generateddog12widget/generated/GeneratedWidget55.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/dogdogapp/generateddog12widget/generated/GeneratedFrame11Widget2.dart';
import 'package:flutterapp/dogdogapp/generateddog12widget/generated/GeneratedWidget54.dart';
import 'package:flutterapp/dogdogapp/generateddog12widget/generated/GeneratedVectorWidget502.dart';

/* Frame dog12
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDog12Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 31.0,
                top: 97.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 140.0,
                child: GeneratedS2Widget1(),
              ),
              Positioned(
                left: 15.0,
                top: 259.0,
                right: null,
                bottom: null,
                width: 333.0,
                height: 265.0,
                child: GeneratedWidget54(),
              ),
              Positioned(
                left: 63.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 240.0,
                height: 69.0,
                child: GeneratedWidget55(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.06944444444444445;
                  double scaleX = (constraints.maxWidth * percentWidth) / 25.0;

                  double percentHeight = 0.0390625;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 25.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.05277777777777778,
                        translateY: constraints.maxHeight * 0.0296875,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget502())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 1.0083333333333333;

                  final double height = constraints.maxHeight * 0.096875;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * -0.008333333333333333,
                        y: constraints.maxHeight * 0.903125,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedFrame11Widget2(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
