import 'package:flutter/material.dart';
import 'package:flutterapp/dogdogapp/generateddog9widget/generated/Generated5Widget.dart';
import 'package:flutterapp/dogdogapp/generateddog9widget/generated/GeneratedFrame11Widget1.dart';
import 'package:flutterapp/dogdogapp/generateddog9widget/generated/GeneratedWidget46.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/dogdogapp/generateddog9widget/generated/GeneratedVectorWidget347.dart';
import 'package:flutterapp/dogdogapp/generateddog9widget/generated/GeneratedB4Widget1.dart';

/* Frame dog9
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDog9Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 43.0,
                top: 97.0,
                right: null,
                bottom: null,
                width: 256.0,
                height: 139.0,
                child: GeneratedB4Widget1(),
              ),
              Positioned(
                left: 10.0,
                top: 269.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 246.0,
                child: Generated5Widget(),
              ),
              Positioned(
                left: 63.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 237.0,
                height: 66.0,
                child: GeneratedWidget46(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.06944444444444445;
                  double scaleX = (constraints.maxWidth * percentWidth) / 25.0;

                  double percentHeight = 0.0390625;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 25.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.05,
                        translateY: constraints.maxHeight * 0.03125,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget347())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 1.0138888888888888;

                  final double height = constraints.maxHeight * 0.096875;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: constraints.maxHeight * 0.9015625,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedFrame11Widget1(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
